// constants.ts
import { TranslationContent, Language } from './types';

export const ADMIN_USERNAME = "283203";
export const ADMIN_PASSWORD = "Faizan@01";

export const TRANSLATIONS: Record<Language, TranslationContent> = {
  en: {
    nav: {
      home: 'Home',
      services: 'Services',
      team: 'Our Team',
      contact: 'Contact',
      imageGeneration: 'AI Image Generation',
      photoEditor: 'Photo Editor',
      requestService: 'Request Service',
      admin: 'Admin',
    },
    hero: {
      title: 'Mohammad Faizan Jan Seva Kendra',
      subtitle: 'Your one-stop solution for all CSC and e-District services. Reliable, fast, and efficient.',
      cta: 'Request a Service',
    },
    services: {
      title: 'Our Services & Rates',
      items: [
        { title: 'State Bank of India Services', description: 'All banking services available.' },
        { title: 'AEPS Services', description: 'All Aadhaar Enabled Payment System services.' },
        { title: 'Lamination', description: 'Document lamination.', price: '₹10' },
        { title: 'Photocopy (Zerox)', description: 'Single-sided: ₹1, Double-sided: ₹2.' },
        { title: 'e-District Certificates', description: 'Domicile, Caste, Income certificates.', price: '₹100' },
        { title: 'Bank Account Opening', description: 'Open a new bank account.', price: 'Free of Cost' },
      ],
      outro: 'All CSC related services are available here. If you need any of our services, please fill out the form with the required details and contact us immediately on any of the provided numbers. Thank you!'
    },
    team: {
      title: 'Our Professional Team',
      members: [
        { name: 'Mohammad Faizan', role: 'Owner' },
        { name: 'Mohammad Shahrukh', role: 'Manager' },
        { name: 'Mohammad Sadiq', role: 'Staff' },
        { name: 'Mohammad Altaf Azam Khan', role: 'Staff' },
      ],
    },
    imageGeneration: {
      title: 'AI Image Generation',
      promptLabel: 'Describe the image you want to create',
      promptPlaceholder: 'e.g., A high-quality logo for a CSC center',
      buttonText: 'Generate Image',
      generatingText: 'Generating...',
    },
    photoEditor: {
      title: 'AI Photo Editor',
      uploadLabel: 'Upload your photo here',
      backgroundRemover: 'Background Remover',
      enhancer: 'Enhancer',
      passportPhoto: 'Passport Photo Maker',
      removeBg: 'Remove Background',
      enhanceImage: 'Enhance Quality',
      formatPassport: 'Format for Passport',
      processing: 'Processing...',
      download: 'Download Image',
      original: 'Original',
      edited: 'Edited',
    },
    serviceRequest: {
      title: 'Service Request & Status',
      nameLabel: 'Full Name',
      namePlaceholder: 'Enter your full name',
      emailLabel: 'Email Address',
      emailPlaceholder: 'Enter your email',
      serviceLabel: 'Select a Service',
      servicePlaceholder: 'Choose a service',
      detailsLabel: 'Additional Details',
      detailsPlaceholder: 'Provide any additional information here',
      submitButton: 'Submit Request',
      statusCheck: 'Check Your Application Status',
      requestIdPlaceholder: 'Enter your request number',
      checkButton: 'Check Status',
      thankYouTitle: 'Thank You!',
      thankYouMessage: 'Your service request has been submitted successfully. A representative from Mohammad Faizan Jan Seva Kendra will contact you shortly.',
      yourRequestId: 'Your Request Number is:',
      statusLabels: {
        pending: 'Pending',
        inProgress: 'In Progress',
        completed: 'Completed',
      },
    },
    contact: {
      title: 'Contact & Location',
      address: 'Kohinoor Road, Noor Nagar, Gali No. 26',
      email: 'faizanjanseva@gmail.com',
      phone: '8534983041 / 9045174146 / 749408345',
      whatsapp: '8534983041 / 9045174146',
      socials: 'Follow Us',
      instagram: '@faizancsc',
    },
    chatbot: {
      title: 'AI Helper',
      placeholder: 'Ask about our services...',
    },
    login: {
      title: 'Admin Login',
      usernameLabel: 'Username',
      passwordLabel: 'Password',
      loginButton: 'Login',
      errorMessage: 'Invalid username or password.',
    },
    adminPanel: {
      title: 'Admin Dashboard',
      welcome: 'Welcome, Admin!',
      logout: 'Logout',
      requestsTitle: 'Current Service Requests',
      headers: {
        id: 'Request ID',
        name: 'Name',
        service: 'Service',
        status: 'Status',
        action: 'Action',
      },
      noRequests: 'No service requests found.',
    },
  },
  hi: {
    nav: {
      home: 'होम',
      services: 'सेवाएं',
      team: 'हमारी टीम',
      contact: 'संपर्क',
      imageGeneration: 'एआई इमेज जेनरेटर',
      photoEditor: 'फोटो एडिटर',
      requestService: 'सेवा का अनुरोध करें',
      admin: 'एडमिन',
    },
    hero: {
      title: 'मोहम्मद फैजान जन सेवा केंद्र',
      subtitle: 'सभी सीएससी और ई-डिस्ट्रिक्ट सेवाओं के लिए आपका वन-स्टॉप समाधान। विश्वसनीय, तेज और कुशल।',
      cta: 'सेवा का अनुरोध करें',
    },
    services: {
      title: 'हमारी सेवाएं और दरें',
      items: [
        { title: 'भारतीय स्टेट बैंक सेवाएं', description: 'सभी बैंकिंग सेवाएं उपलब्ध हैं।' },
        { title: 'एईपीएस सेवाएं', description: 'सभी आधार सक्षम भुगतान प्रणाली सेवाएं।' },
        { title: 'लेमिनेशन', description: 'दस्तावेज़ लेमिनेशन।', price: '₹10' },
        { title: 'फोटोकॉपी (ज़ीरॉक्स)', description: 'एक तरफा: ₹1, दोनों तरफा: ₹2' },
        { title: 'ई-डिस्ट्रिक्ट प्रमाण पत्र', description: 'मूल निवास, जाति, आय प्रमाण पत्र।', price: '₹100' },
        { title: 'बैंक खाता खोलना', description: 'नया बैंक खाता खोलें।', price: 'निःशुल्क' },
      ],
      outro: 'सीएससी से जुडी सभी सर्विस यहाँ पर उपलब्ध है। अगर किसी को हमारी सर्विस चाहिए तो पहले सर्विस के हिसाब से फॉर्म भरिये जो डिटेल मैंडेटरी है उन्हें भरिये और ये करने के बाद हमें तुरंत कांटेक्ट करे इनमे से किसी भी नंबर पर। धन्यवाद!'
    },
    team: {
      title: 'हमारी पेशेवर टीम',
      members: [
        { name: 'मोहम्मद फैजान', role: 'मालिक' },
        { name: 'मोहम्मद शाहरुख', role: 'प्रबंधक' },
        { name: 'मोहम्मद सादिक', role: 'कर्मचारी' },
        { name: 'मोहम्मद अल्ताफ आजम खान', role: 'कर्मचारी' },
      ],
    },
    imageGeneration: {
      title: 'एआई इमेज जेनरेटर',
      promptLabel: 'आप जो इमेज बनाना चाहते हैं उसका वर्णन करें',
      promptPlaceholder: 'जैसे, एक सीएससी केंद्र के लिए उच्च गुणवत्ता वाला लोगो',
      buttonText: 'इमेज बनाएं',
      generatingText: 'बनाया जा रहा है...',
    },
    photoEditor: {
      title: 'एआई फोटो एडिटर',
      uploadLabel: 'अपनी तस्वीर यहां अपलोड करें',
      backgroundRemover: 'बैकग्राउंड रिमूवर',
      enhancer: 'एन्हांसर',
      passportPhoto: 'पासपोर्ट फोटो मेकर',
      removeBg: 'बैकग्राउंड हटाएं',
      enhanceImage: 'गुणवत्ता बढ़ाएं',
      formatPassport: 'पासपोर्ट के लिए प्रारूप',
      processing: 'प्रोसेसिंग हो रही है...',
      download: 'इमेज डाउनलोड करें',
      original: 'मूल',
      edited: 'संपादित',
    },
    serviceRequest: {
      title: 'सेवा अनुरोध और स्थिति',
      nameLabel: 'पूरा नाम',
      namePlaceholder: 'अपना पूरा नाम दर्ज करें',
      emailLabel: 'ईमेल पता',
      emailPlaceholder: 'अपना ईमेल दर्ज करें',
      serviceLabel: 'एक सेवा चुनें',
      servicePlaceholder: 'एक सेवा चुनें',
      detailsLabel: 'अतिरिक्त विवरण',
      detailsPlaceholder: 'यहां कोई अतिरिक्त जानकारी प्रदान करें',
      submitButton: 'अनुरोध भेजें',
      statusCheck: 'अपने आवेदन की स्थिति जांचें',
      requestIdPlaceholder: 'अपना अनुरोध संख्या दर्ज करें',
      checkButton: 'स्थिति जांचें',
      thankYouTitle: 'धन्यवाद!',
      thankYouMessage: 'आपकी सेवा का अनुरोध सफलतापूर्वक सबमिट कर दिया गया है। मोहम्मद फैजान जन सेवा केंद्र का एक प्रतिनिधि जल्द ही आपसे संपर्क करेगा।',
      yourRequestId: 'आपका अनुरोध संख्या है:',
      statusLabels: {
        pending: 'लंबित',
        inProgress: 'प्रगति में है',
        completed: 'पूरा हो गया',
      },
    },
    contact: {
      title: 'संपर्क और स्थान',
      address: 'कोहिनूर रोड, नूर नगर, गली नंबर 26',
      email: 'faizanjanseva@gmail.com',
      phone: '8534983041 / 9045174146 / 749408345',
      whatsapp: '8534983041 / 9045174146',
      socials: 'हमें फॉलो करें',
      instagram: '@faizancsc',
    },
    chatbot: {
      title: 'एआई सहायक',
      placeholder: 'हमारी सेवाओं के बारे में पूछें...',
    },
    login: {
      title: 'एडमिन लॉगिन',
      usernameLabel: 'उपयोगकर्ता नाम',
      passwordLabel: 'पासवर्ड',
      loginButton: 'लॉग इन करें',
      errorMessage: 'अमान्य उपयोगकर्ता नाम या पासवर्ड।',
    },
    adminPanel: {
      title: 'एडमिन डैशबोर्ड',
      welcome: 'स्वागत है, एडमिन!',
      logout: 'लॉग आउट',
      requestsTitle: 'वर्तमान सेवा अनुरोध',
      headers: {
        id: 'अनुरोध आईडी',
        name: 'नाम',
        service: 'सेवा',
        status: 'स्थिति',
        action: 'कार्यवाही',
      },
      noRequests: 'कोई सेवा अनुरोध नहीं मिला।',
    },
  },
};
